steps:
  - id: Update Permissions
    name: "gcr.io/cloud-builders/git"
    entrypoint: "chmod"
    args: ["-v","-R", "a+rw","."]
  - id: Build Jekyll Site
    name: 'jekyll/jekyll'
    args: ['jekyll','build']
  - id: Deploy to App Engine
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "15m"
